export const PICK_UP_BLOCK = 'PICK_UP_BLOCK';
export const SET_DOWN_BLOCK = 'SET_DOWN_BLOCK';
export const MOVE_BLOCK = 'MOVE_BLOCK';
export const RESET_BLOCK = 'RESET_BLOCK';
export const SET_STARTER_POSITION = 'SET_STARTER_POSITION';
export const SET_BOARD_POSITION = 'SET_BOARD_POSITION';
export const SET_STARTER_NAMES = 'SET_STARTER_NAMES'